---
title: "Extension Project Background"
output: html_notebook
---
```{r}

# setup
library(tidyverse)
library(lubridate)
library(scales)
theme_set(theme_bw())

# read in nyc data
nyc_incidents <- read_csv('data/nyc_incidents.csv')
View(nyc_incidents)

nyc_incidents <- nyc_incidents %>%
  # convert the date of the incident into a Date
  mutate(IncidentDate = as.Date(parse_datetime(IncidentDate, "%m/%d/%Y"))) %>%
  drop_na(IncidentDate)
 
# count number of incidents in each month of each year
nyc_incidents <- nyc_incidents %>% 
  # put data into groups of month and year
  group_by(floor_date(IncidentDate, unit = "month")) %>%
  rename(IncidentMonth = 'floor_date(IncidentDate, unit = "month")') %>%
  # count the number of incidents in each group
  summarise(NumIncidents = n()) %>%
  ungroup()
View(nyc_incidents)

nyc_incidents %>% ggplot(aes(x = IncidentMonth, y = NumIncidents)) +
  geom_point() +
  scale_x_date(breaks = "month") +
  geom_smooth()

```

```{r}

# setup
library(tidyverse)
library(lubridate)
library(scales)
theme_set(theme_bw())

# read in nyc data
nyc_incidents <- read_csv('data/nyc_incidents.csv')
View(nyc_incidents)

# count number of incidents by officers of each gender against people of each gender
nyc_incidents <- nyc_incidents %>%
  # group by impacted gender and officer gender
  group_by(ImpactedGender, OfficerGender) %>%
  # count number of allegations in each category
  summarize(num = n()) %>%
  # find the percentage of allegations in each category
  mutate(PercentOfAllIncidents = num / sum(num))
View(nyc_incidents)

nyc_incidents %>% ggplot() +
  geom_bar(aes(x = ImpactedGender, y = PercentOfAllIncidents, color = OfficerGender, fill = OfficerGender), 
           stat = "identity", 
           position="dodge")


```
```{r}

# setup
library(tidyverse)
library(lubridate)
library(scales)
theme_set(theme_bw())

# read in nyc data
nyc_incidents <- read_csv('data/nyc_incidents.csv')
View(nyc_incidents)

# count number of incidents per officer rank
nyc_incidents <- nyc_incidents %>%
  group_by(IncidentRankLong) %>%
  summarize(NumIncidents = n())
View(nyc_incidents)

nyc_incidents %>% ggplot(aes(x = "", y = NumIncidents / sum(NumIncidents), fill = IncidentRankLong)) +
  geom_bar(stat = "identity") +
  coord_polar("y", start = 0) +
  geom_text(aes(label = NumIncidents / sum(NumIncidents)), color = "white") +
  theme_void()
  

```

```{r}

# setup
library(tidyverse)
library(lubridate)
library(scales)
theme_set(theme_bw())

# read in nyc data
nyc_incidents <- read_csv('data/nyc_incidents.csv')
View(nyc_incidents)

nyc_incidents <- nyc_incidents %>%
  # convert the date of the incident into a Date
  mutate(IncidentDate = as.Date(parse_datetime(IncidentDate, "%m/%d/%Y"))) %>%
  drop_na(IncidentDate)

# add a column to indicate if an officer increased in rank since the incident
nyc_incidents <- nyc_incidents %>%
  group_by(OfficerID) %>%
  arrange(IncidentDate) %>%
  slice(1) %>%
  mutate(ChangedRank = CurrentRankLong == IncidentRankLong)
View(nyc_incidents)

nyc_incidents %>% ggplot(aes(x = ChangedRank)) +
  geom_bar()


```

```{r}

# setup
library(tidyverse)
library(lubridate)
library(scales)
theme_set(theme_bw())

# read in nyc data
nyc_incidents <- read_csv('data/nyc_incidents.csv')
View(nyc_incidents)



```


```{r}

# setup
library(tidyverse)
library(lubridate)
library(scales)
theme_set(theme_bw())

# read in data

philly_incidents_findings_from_open_data_philly <- 
  read_csv('data/philly_incidents_findings_from_open_data_philly.csv')
View(philly_incidents_findings_from_open_data_philly)

philly_complainant_demographics_from_open_data_philly <- 
  read_csv('data/philly_complainant_demographics_from_open_data_philly.csv')
View(philly_complainant_demographics_from_open_data_philly)

# clean data

philly_incidents_findings_from_open_data_philly <- philly_incidents_findings_from_open_data_philly %>%
  select(complaint_id, po_sex, investigative_findings)
View(philly_incidents_findings_from_open_data_philly)

philly_complainant_demographics_from_open_data_philly <- philly_complainant_demographics_from_open_data_philly %>%
  select(complaint_id, complainant_sex)
View(philly_complainant_demographics_from_open_data_philly)

# join philly_incidents_findings_from_open_data_philly and philly_complainant_demographics_from_open_data_philly
philly_findings_and_demographics_from_open_data_philly <- 
  inner_join(philly_incidents_findings_from_open_data_philly, 
             philly_complainant_demographics_from_open_data_philly, 
             by = "complaint_id")
View(philly_findings_and_demographics_from_open_data_philly)

# separate the incidents with sustained findings into groups by po_sex and complainant_sex
philly_sustained_findings_and_demographics_from_open_data_philly <- 
  philly_findings_and_demographics_from_open_data_philly %>%
  filter(investigative_findings == "Sustained Finding") %>%
  mutate(po_sex_and_complainant_sex = case_when(po_sex == "male" & complainant_sex == "male" ~ "MM",
                                                po_sex == "male" & complainant_sex == "female" ~ "MF",
                                                po_sex == "female" & complainant_sex == "male" ~ "FM",
                                                po_sex == "female" & complainant_sex == "female" ~ "FF"))
View(philly_sustained_findings_and_demographics_from_open_data_philly)

# count the number of incidents in each category
philly_sustained_findings_and_demographics_from_open_data_philly <- 
  philly_sustained_findings_and_demographics_from_open_data_philly %>%
  group_by(po_sex_and_complainant_sex) %>%
  summarize(count_in_this_category = n())
View(philly_sustained_findings_and_demographics_from_open_data_philly)

philly_sustained_findings_and_demographics_from_open_data_philly %>% 
  ggplot(aes(x = "", y = count_in_this_category / sum(count_in_this_category), fill = po_sex_and_complainant_sex)) +
  geom_bar(stat = "identity") +
  coord_polar("y", start = 0) +
  geom_text(aes(label = count_in_this_category / sum(count_in_this_category)), color = "white") +
  theme_void()





# separate the incidents without sustained findings into groups by po_sex and complainant_sex
philly_no_sustained_findings_and_demographics_from_open_data_philly <- 
  philly_findings_and_demographics_from_open_data_philly %>%
  filter(investigative_findings == "No Sustained Findings") %>%
  mutate(po_sex_and_complainant_sex = case_when(po_sex == "male" & complainant_sex == "male" ~ "MM",
                                                po_sex == "male" & complainant_sex == "female" ~ "MF",
                                                po_sex == "female" & complainant_sex == "male" ~ "FM",
                                                po_sex == "female" & complainant_sex == "female" ~ "FF"))
View(philly_no_sustained_findings_and_demographics_from_open_data_philly)

# count the number of incidents in each category
philly_no_sustained_findings_and_demographics_from_open_data_philly <- 
  philly_no_sustained_findings_and_demographics_from_open_data_philly %>%
  group_by(po_sex_and_complainant_sex) %>%
  summarize(count_in_this_category = n())
View(philly_no_sustained_findings_and_demographics_from_open_data_philly)

philly_no_sustained_findings_and_demographics_from_open_data_philly %>% 
  ggplot(aes(x = "", y = count_in_this_category / sum(count_in_this_category), fill = po_sex_and_complainant_sex)) +
  geom_bar(stat = "identity") +
  coord_polar("y", start = 0) +
  geom_text(aes(label = count_in_this_category / sum(count_in_this_category)), color = "white") +
  theme_void()



```













```{r sustained findings}
# separate the incidents with sustained findings into groups by po_sex and complainant_sex
philly_sustained_findings_and_demographics_from_open_data_philly <- 
  philly_findings_and_demographics_from_open_data_philly %>%
  filter(investigative_findings == "Sustained Finding") %>%
  # add a column with encoding to indicate the sex of the po and the complainant
  # (M = Male, F = Female)
  mutate(po_sex_and_complainant_sex = case_when(po_sex == "male" & complainant_sex == "male" ~ "MM",
                                                po_sex == "male" & complainant_sex == "female" ~ "MF",
                                                po_sex == "female" & complainant_sex == "male" ~ "FM",
                                                po_sex == "female" & complainant_sex == "female" ~ "FF"))
# View(philly_sustained_findings_and_demographics_from_open_data_philly)

# count the number of incidents in each category and calculate the proportion of the total
philly_sustained_findings_and_demographics_from_open_data_philly <- 
  philly_sustained_findings_and_demographics_from_open_data_philly %>%
  group_by(po_sex_and_complainant_sex) %>%
  # count the number of incidents in each category
  summarize(count_in_this_category = n()) %>%
  # calculate the proportion
  mutate(proportion = count_in_this_category / sum(count_in_this_category))
# View(philly_sustained_findings_and_demographics_from_open_data_philly)

# pie chart
philly_sustained_findings_and_demographics_from_open_data_philly %>% 
  ggplot(aes(x = "", y = proportion, fill = po_sex_and_complainant_sex)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y", start = 0) +
  # label each segment in the chart
  geom_text(aes(label = percent(proportion)), position = position_stack(vjust = 0.6)) +
  theme_void() +
  # set the key
  scale_fill_discrete("PO Sex and Complainant Sex", 
                      labels = c("Female-Female", "Female-Male", "Male-Female", "Male-Male")) +
  # title the chart
  ggtitle("Percent of Complaints with Sustained Findings by PO Sex and Complainant Sex")

```

```{r no sustained findings}

# separate the incidents without sustained findings into groups by po_sex and complainant_sex
philly_no_sustained_findings_and_demographics_from_open_data_philly <- 
  philly_findings_and_demographics_from_open_data_philly %>%
  filter(investigative_findings == "No Sustained Findings") %>%
  # add a column with encoding to indicate the sex of the po and the complainant
  # (M = Male, F = Female)
  mutate(po_sex_and_complainant_sex = case_when(po_sex == "male" & complainant_sex == "male" ~ "MM",
                                                po_sex == "male" & complainant_sex == "female" ~ "MF",
                                                po_sex == "female" & complainant_sex == "male" ~ "FM",
                                                po_sex == "female" & complainant_sex == "female" ~ "FF"))
# View(philly_no_sustained_findings_and_demographics_from_open_data_philly)

# count the number of incidents in each category and calculate the proportion of the total
philly_no_sustained_findings_and_demographics_from_open_data_philly <- 
  philly_no_sustained_findings_and_demographics_from_open_data_philly %>%
  group_by(po_sex_and_complainant_sex) %>%
  # count the number of incidents in each category
  summarize(count_in_this_category = n()) %>%
  # calculate the proportion
  mutate(proportion = count_in_this_category / sum(count_in_this_category))
# View(philly_no_sustained_findings_and_demographics_from_open_data_philly)

philly_no_sustained_findings_and_demographics_from_open_data_philly %>% 
  ggplot(aes(x = "", y = proportion, fill = po_sex_and_complainant_sex)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y", start = 0) +
  # label each segment in the chart
  geom_text(aes(label = percent(proportion)), position = position_stack(vjust = 0.6)) +
  theme_void() +
  # set the key
  scale_fill_discrete("PO Sex and Complainant Sex",
                      labels = c("Female-Female", "Female-Male", "Male-Female", "Male-Male")) +
  # title the chart
  ggtitle("Percent of Complaints with No Sustained Findings by PO Sex and Complainant Sex")
    
```








